/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author 10918857104
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Sistema de Vendas e Compras");
        setExtendedState(MAXIMIZED_BOTH);
       // JDlgTelaLogin jDlgTelaLogin = new JDlgTelaLogin(this,true);
       // jDlgTelaLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBtnVendedorCon = new javax.swing.JButton();
        jBtnProdutosCon = new javax.swing.JButton();
        jBtnClientesCadas = new javax.swing.JButton();
        jBtnUsuariosCadas = new javax.swing.JButton();
        jBtnVendasMov = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuCadastros = new javax.swing.JMenu();
        jMnuClientes = new javax.swing.JMenuItem();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuEntregas = new javax.swing.JMenuItem();
        jMnuProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVendas = new javax.swing.JMenuItem();
        jMnuMovimento1 = new javax.swing.JMenu();
        jMnuProdConsul = new javax.swing.JMenuItem();
        jMnuUsuConsul = new javax.swing.JMenuItem();
        jMnuVendasConsul = new javax.swing.JMenuItem();
        jMnuVendedorConsul = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jBtnVendedorCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-homem-com-dinheiro-24.png"))); // NOI18N
        jBtnVendedorCon.setFocusable(false);
        jBtnVendedorCon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendedorCon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendedorCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendedorConActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendedorCon);

        jBtnProdutosCon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrinho11.png"))); // NOI18N
        jBtnProdutosCon.setToolTipText("");
        jBtnProdutosCon.setFocusable(false);
        jBtnProdutosCon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnProdutosCon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnProdutosCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProdutosConActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnProdutosCon);

        jBtnClientesCadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-clientes-24.png"))); // NOI18N
        jBtnClientesCadas.setFocusable(false);
        jBtnClientesCadas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnClientesCadas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnClientesCadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnClientesCadasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnClientesCadas);

        jBtnUsuariosCadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cliente-24.png"))); // NOI18N
        jBtnUsuariosCadas.setFocusable(false);
        jBtnUsuariosCadas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnUsuariosCadas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnUsuariosCadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUsuariosCadasActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnUsuariosCadas);

        jBtnVendasMov.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aperto-de-mao.png"))); // NOI18N
        jBtnVendasMov.setFocusable(false);
        jBtnVendasMov.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnVendasMov.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnVendasMov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVendasMovActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnVendasMov);

        jMnuCadastros.setText("Cadastros");

        jMnuClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-clientes-24.png"))); // NOI18N
        jMnuClientes.setText("Clientes");
        jMnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientesActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuClientes);

        jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-cliente-24.png"))); // NOI18N
        jMnuUsuarios.setText("Usuários");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuUsuarios);

        jMnuEntregas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuEntregas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-homem-com-dinheiro-24.png"))); // NOI18N
        jMnuEntregas.setText("Vendedor");
        jMnuEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuEntregasActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuEntregas);

        jMnuProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrinho-de-compras1.png"))); // NOI18N
        jMnuProdutos.setText("Produtos");
        jMnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdutosActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuProdutos);
        jMnuCadastros.add(jSeparator1);

        jMnuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-retornar-24.png"))); // NOI18N
        jMnuSair.setText("Sair");
        jMnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSairActionPerformed(evt);
            }
        });
        jMnuCadastros.add(jMnuSair);

        jMenuBar1.add(jMnuCadastros);

        jMnuMovimento.setText("Movimento");

        jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aperto-de-mao.png"))); // NOI18N
        jMnuVendas.setText("Vendas");
        jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuVendas);

        jMenuBar1.add(jMnuMovimento);

        jMnuMovimento1.setText("Consultas");

        jMnuProdConsul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProdConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrinho11.png"))); // NOI18N
        jMnuProdConsul.setText("Produtos");
        jMnuProdConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProdConsulActionPerformed(evt);
            }
        });
        jMnuMovimento1.add(jMnuProdConsul);

        jMnuUsuConsul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-clientes-24.png"))); // NOI18N
        jMnuUsuConsul.setText("Usuarios");
        jMnuUsuConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuConsulActionPerformed(evt);
            }
        });
        jMnuMovimento1.add(jMnuUsuConsul);

        jMnuVendasConsul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendasConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/aperto-de-mao.png"))); // NOI18N
        jMnuVendasConsul.setText("Vendas");
        jMnuVendasConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendasConsulActionPerformed(evt);
            }
        });
        jMnuMovimento1.add(jMnuVendasConsul);

        jMnuVendedorConsul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedorConsul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-homem-com-dinheiro-24.png"))); // NOI18N
        jMnuVendedorConsul.setText("Vendedor");
        jMnuVendedorConsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedorConsulActionPerformed(evt);
            }
        });
        jMnuMovimento1.add(jMnuVendedorConsul);

        jMenuBar1.add(jMnuMovimento1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientesActionPerformed
        JDlgClientes jDlgClientes = new JDlgClientes(this, true);
        jDlgClientes.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuClientesActionPerformed

    private void jMnuEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuEntregasActionPerformed
        JDlgVendedor jDlgEntregas = new JDlgVendedor(this, true);
        jDlgEntregas.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuEntregasActionPerformed

    private void jMnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdutosActionPerformed
        // TODO add your handling code here:
        JDlgProdutos jDlgProdutos = new JDlgProdutos(this, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuProdutosActionPerformed

    private void jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasActionPerformed
        JDlgVendas jDlgVendas = new JDlgVendas(this, true);
        jDlgVendas.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_jMnuVendasActionPerformed

    private void jMnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMnuSairActionPerformed

    private void jMnuProdConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProdConsulActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProdutos consultaProdutos = new JDlgConsultaProdutos(this, true);
        consultaProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuProdConsulActionPerformed

    private void jMnuUsuConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuConsulActionPerformed
        // TODO add your handling code here:]
       JDlgConsultaUsuarios consultaUsuarios = new JDlgConsultaUsuarios(this, true);
       consultaUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuConsulActionPerformed

    private void jMnuVendasConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendasConsulActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendas consultaVendas = new JDlgConsultaVendas(this, true);
        consultaVendas.setVisible(true);
    }//GEN-LAST:event_jMnuVendasConsulActionPerformed

    private void jMnuVendedorConsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedorConsulActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendedor consultaVendedor = new JDlgConsultaVendedor(this, true);
        consultaVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuVendedorConsulActionPerformed

    private void jBtnVendedorConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendedorConActionPerformed
        // TODO add your handling code here:
        new JDlgVendedor(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnVendedorConActionPerformed

    private void jBtnProdutosConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProdutosConActionPerformed
        // TODO add your handling code here:
       new JDlgProdutos(this, rootPaneCheckingEnabled).setVisible(true); 
    }//GEN-LAST:event_jBtnProdutosConActionPerformed

    private void jBtnClientesCadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnClientesCadasActionPerformed
        // TODO add your handling code here:
        new JDlgClientes(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnClientesCadasActionPerformed

    private void jBtnUsuariosCadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUsuariosCadasActionPerformed
        // TODO add your handling code here:
        new JDlgUsuarios(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnUsuariosCadasActionPerformed

    private void jBtnVendasMovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVendasMovActionPerformed
        // TODO add your handling code here:
        new JDlgVendas(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_jBtnVendasMovActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnClientesCadas;
    private javax.swing.JButton jBtnProdutosCon;
    private javax.swing.JButton jBtnUsuariosCadas;
    private javax.swing.JButton jBtnVendasMov;
    private javax.swing.JButton jBtnVendedorCon;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuCadastros;
    private javax.swing.JMenuItem jMnuClientes;
    private javax.swing.JMenuItem jMnuEntregas;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenu jMnuMovimento1;
    private javax.swing.JMenuItem jMnuProdConsul;
    private javax.swing.JMenuItem jMnuProdutos;
    private javax.swing.JMenuItem jMnuSair;
    private javax.swing.JMenuItem jMnuUsuConsul;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JMenuItem jMnuVendas;
    private javax.swing.JMenuItem jMnuVendasConsul;
    private javax.swing.JMenuItem jMnuVendedorConsul;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
