package bean;
// Generated 12/10/2025 19:53:29 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlrClientes generated by hbm2java
 */
@Entity
@Table(name="jlr_clientes"
    ,catalog="joao_roa"
)
public class JlrClientes  implements java.io.Serializable {


     private int idJlrClientes;
     private String jlrNome;
     private String jlrCpf;
     private String jlrRg;
     private Date jlrDataNascimento;
     private String jlrTelefone;
     private String jlrEmail;
     private String jlrEndereco;
     private String jlrCidade;
     private String jlrEstado;
     private String jlrCep;
     private Date jlrDataCadastro;
     private String jlrPreferenciaSabor;
     private String jlrAlergias;
     private String jlrObservacoes;

    public JlrClientes() {
    }

	
    public JlrClientes(int idJlrClientes, String jlrNome, String jlrCpf, String jlrRg, String jlrTelefone, String jlrEmail, String jlrEndereco, String jlrCidade, String jlrEstado, String jlrCep) {
        this.idJlrClientes = idJlrClientes;
        this.jlrNome = jlrNome;
        this.jlrCpf = jlrCpf;
        this.jlrRg = jlrRg;
        this.jlrTelefone = jlrTelefone;
        this.jlrEmail = jlrEmail;
        this.jlrEndereco = jlrEndereco;
        this.jlrCidade = jlrCidade;
        this.jlrEstado = jlrEstado;
        this.jlrCep = jlrCep;
    }
    public JlrClientes(int idJlrClientes, String jlrNome, String jlrCpf, String jlrRg, Date jlrDataNascimento, String jlrTelefone, String jlrEmail, String jlrEndereco, String jlrCidade, String jlrEstado, String jlrCep, Date jlrDataCadastro, String jlrPreferenciaSabor, String jlrAlergias, String jlrObservacoes) {
       this.idJlrClientes = idJlrClientes;
       this.jlrNome = jlrNome;
       this.jlrCpf = jlrCpf;
       this.jlrRg = jlrRg;
       this.jlrDataNascimento = jlrDataNascimento;
       this.jlrTelefone = jlrTelefone;
       this.jlrEmail = jlrEmail;
       this.jlrEndereco = jlrEndereco;
       this.jlrCidade = jlrCidade;
       this.jlrEstado = jlrEstado;
       this.jlrCep = jlrCep;
       this.jlrDataCadastro = jlrDataCadastro;
       this.jlrPreferenciaSabor = jlrPreferenciaSabor;
       this.jlrAlergias = jlrAlergias;
       this.jlrObservacoes = jlrObservacoes;
    }
   
     @Id 

    
    @Column(name="id_jlr_clientes", unique=true, nullable=false)
    public int getIdJlrClientes() {
        return this.idJlrClientes;
    }
    
    public void setIdJlrClientes(int idJlrClientes) {
        this.idJlrClientes = idJlrClientes;
    }

    
    @Column(name="jlr_nome", nullable=false, length=50)
    public String getJlrNome() {
        return this.jlrNome;
    }
    
    public void setJlrNome(String jlrNome) {
        this.jlrNome = jlrNome;
    }

    
    @Column(name="jlr_cpf", nullable=false, length=11)
    public String getJlrCpf() {
        return this.jlrCpf;
    }
    
    public void setJlrCpf(String jlrCpf) {
        this.jlrCpf = jlrCpf;
    }

    
    @Column(name="jlr_rg", nullable=false, length=12)
    public String getJlrRg() {
        return this.jlrRg;
    }
    
    public void setJlrRg(String jlrRg) {
        this.jlrRg = jlrRg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jlr_data_nascimento", length=10)
    public Date getJlrDataNascimento() {
        return this.jlrDataNascimento;
    }
    
    public void setJlrDataNascimento(Date jlrDataNascimento) {
        this.jlrDataNascimento = jlrDataNascimento;
    }

    
    @Column(name="jlr_telefone", nullable=false, length=15)
    public String getJlrTelefone() {
        return this.jlrTelefone;
    }
    
    public void setJlrTelefone(String jlrTelefone) {
        this.jlrTelefone = jlrTelefone;
    }

    
    @Column(name="jlr_email", nullable=false, length=80)
    public String getJlrEmail() {
        return this.jlrEmail;
    }
    
    public void setJlrEmail(String jlrEmail) {
        this.jlrEmail = jlrEmail;
    }

    
    @Column(name="jlr_endereco", nullable=false, length=65535)
    public String getJlrEndereco() {
        return this.jlrEndereco;
    }
    
    public void setJlrEndereco(String jlrEndereco) {
        this.jlrEndereco = jlrEndereco;
    }

    
    @Column(name="jlr_cidade", nullable=false, length=50)
    public String getJlrCidade() {
        return this.jlrCidade;
    }
    
    public void setJlrCidade(String jlrCidade) {
        this.jlrCidade = jlrCidade;
    }

    
    @Column(name="jlr_estado", nullable=false, length=2)
    public String getJlrEstado() {
        return this.jlrEstado;
    }
    
    public void setJlrEstado(String jlrEstado) {
        this.jlrEstado = jlrEstado;
    }

    
    @Column(name="jlr_cep", nullable=false, length=9)
    public String getJlrCep() {
        return this.jlrCep;
    }
    
    public void setJlrCep(String jlrCep) {
        this.jlrCep = jlrCep;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jlr_data_cadastro", length=19)
    public Date getJlrDataCadastro() {
        return this.jlrDataCadastro;
    }
    
    public void setJlrDataCadastro(Date jlrDataCadastro) {
        this.jlrDataCadastro = jlrDataCadastro;
    }

    
    @Column(name="jlr_preferencia_sabor", length=50)
    public String getJlrPreferenciaSabor() {
        return this.jlrPreferenciaSabor;
    }
    
    public void setJlrPreferenciaSabor(String jlrPreferenciaSabor) {
        this.jlrPreferenciaSabor = jlrPreferenciaSabor;
    }

    
    @Column(name="jlr_alergias", length=65535)
    public String getJlrAlergias() {
        return this.jlrAlergias;
    }
    
    public void setJlrAlergias(String jlrAlergias) {
        this.jlrAlergias = jlrAlergias;
    }

    
    @Column(name="jlr_observacoes", length=65535)
    public String getJlrObservacoes() {
        return this.jlrObservacoes;
    }
    
    public void setJlrObservacoes(String jlrObservacoes) {
        this.jlrObservacoes = jlrObservacoes;
    }




}


