package bean;
// Generated 29/10/2025 15:23:18 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlrProdutos generated by hbm2java
 */
@Entity
@Table(name="jlr_produtos"
    ,catalog="db_joao_roa"
)
public class JlrProdutos  implements java.io.Serializable {


     private int idJlrProdutos;
     private String jlrNome;
     private String jlrDescricao;
     private Double jlrPreco;
     private String jlrTipo;
     private int jlrEstoque;
     private Date jlrDataCadastro;
     private Set jlrVendasprodutoses = new HashSet(0);

    public JlrProdutos() {
    }

	
    public JlrProdutos(int idJlrProdutos, String jlrNome, String jlrDescricao, Double jlrPreco, String jlrTipo, int jlrEstoque, Date jlrDataCadastro) {
        this.idJlrProdutos = idJlrProdutos;
        this.jlrNome = jlrNome;
        this.jlrDescricao = jlrDescricao;
        this.jlrPreco = jlrPreco;
        this.jlrTipo = jlrTipo;
        this.jlrEstoque = jlrEstoque;
        this.jlrDataCadastro = jlrDataCadastro;
    }
    public JlrProdutos(int idJlrProdutos, String jlrNome, String jlrDescricao, Double jlrPreco, String jlrTipo, int jlrEstoque, Date jlrDataCadastro, Set jlrVendasprodutoses) {
       this.idJlrProdutos = idJlrProdutos;
       this.jlrNome = jlrNome;
       this.jlrDescricao = jlrDescricao;
       this.jlrPreco = jlrPreco;
       this.jlrTipo = jlrTipo;
       this.jlrEstoque = jlrEstoque;
       this.jlrDataCadastro = jlrDataCadastro;
       this.jlrVendasprodutoses = jlrVendasprodutoses;
    }
   
     @Id 

    
    @Column(name="id_jlr_produtos", unique=true, nullable=false)
    public int getIdJlrProdutos() {
        return this.idJlrProdutos;
    }
    
    public void setIdJlrProdutos(int idJlrProdutos) {
        this.idJlrProdutos = idJlrProdutos;
    }

    
    @Column(name="jlr_nome", nullable=false, length=50)
    public String getJlrNome() {
        return this.jlrNome;
    }
    
    public void setJlrNome(String jlrNome) {
        this.jlrNome = jlrNome;
    }

    
    @Column(name="jlr_descricao", nullable=false, length=65535)
    public String getJlrDescricao() {
        return this.jlrDescricao;
    }
    
    public void setJlrDescricao(String jlrDescricao) {
        this.jlrDescricao = jlrDescricao;
    }

    
    @Column(name="jlr_preco", nullable=false, precision=10)
    public Double getJlrPreco() {
        return this.jlrPreco;
    }
    
    public void setJlrPreco(Double jlrPreco) {
        this.jlrPreco = jlrPreco;
    }

    
    @Column(name="jlr_tipo", nullable=false, length=20)
    public String getJlrTipo() {
        return this.jlrTipo;
    }
    
    public void setJlrTipo(String jlrTipo) {
        this.jlrTipo = jlrTipo;
    }

    
    @Column(name="jlr_estoque", nullable=false)
    public int getJlrEstoque() {
        return this.jlrEstoque;
    }
    
    public void setJlrEstoque(int jlrEstoque) {
        this.jlrEstoque = jlrEstoque;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jlr_data_cadastro", nullable=false, length=10)
    public Date getJlrDataCadastro() {
        return this.jlrDataCadastro;
    }
    
    public void setJlrDataCadastro(Date jlrDataCadastro) {
        this.jlrDataCadastro = jlrDataCadastro;
    }

    
    public void setJlrVendasprodutoses(Set jlrVendasprodutoses) {
        this.jlrVendasprodutoses = jlrVendasprodutoses;
    }
    
public String toString() {
        return this.idJlrProdutos + " - " + this.jlrNome;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof JlrProdutos) {
            JlrProdutos jlrProdutos = (JlrProdutos) object;
            if (jlrProdutos.getIdJlrProdutos() == this.getIdJlrProdutos()) {
                return true;
            }
        }
        return false;
    }

}



