package bean;
// Generated 29/10/2025 15:23:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlrUsuarios generated by hbm2java
 */
@Entity
@Table(name="jlr_usuarios"
    ,catalog="db_joao_roa"
)
public class JlrUsuarios  implements java.io.Serializable {


     private int idJlrUsuarios;
     private String jlrNome;
     private String jlrApelido;
     private String jlrCpf;
     private Date jlrDataNascimento;
     private String jlrSenha;
     private int jlrNivel;
     private String jlrAtivo;

    public JlrUsuarios() {
    }

	
    public JlrUsuarios(int idJlrUsuarios, String jlrNome, String jlrApelido, String jlrCpf, Date jlrDataNascimento, String jlrSenha, int jlrNivel, String jlrAtivo) {
        this.idJlrUsuarios = idJlrUsuarios;
        this.jlrNome = jlrNome;
        this.jlrApelido = jlrApelido;
        this.jlrCpf = jlrCpf;
        this.jlrDataNascimento = jlrDataNascimento;
        this.jlrSenha = jlrSenha;
        this.jlrNivel = jlrNivel;
        this.jlrAtivo = jlrAtivo;
    }
    
   
     @Id 

    
    @Column(name="id_jlr_usuarios", unique=true, nullable=false)
    public int getIdJlrUsuarios() {
        return this.idJlrUsuarios;
    }
    
    public void setIdJlrUsuarios(int idJlrUsuarios) {
        this.idJlrUsuarios = idJlrUsuarios;
    }

    
    @Column(name="jlr_nome", nullable=false, length=50)
    public String getJlrNome() {
        return this.jlrNome;
    }
    
    public void setJlrNome(String jlrNome) {
        this.jlrNome = jlrNome;
    }

    
    @Column(name="jlr_apelido", nullable=false, length=50)
    public String getJlrApelido() {
        return this.jlrApelido;
    }
    
    public void setJlrApelido(String jlrApelido) {
        this.jlrApelido = jlrApelido;
    }

    
    @Column(name="jlr_cpf", nullable=false, length=15)
    public String getJlrCpf() {
        return this.jlrCpf;
    }
    
    public void setJlrCpf(String jlrCpf) {
        this.jlrCpf = jlrCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jlr_dataNascimento", nullable=false, length=10)
    public Date getJlrDataNascimento() {
        return this.jlrDataNascimento;
    }
    
    public void setJlrDataNascimento(Date jlrDataNascimento) {
        this.jlrDataNascimento = jlrDataNascimento;
    }

    
    @Column(name="jlr_senha", nullable=false, length=20)
    public String getJlrSenha() {
        return this.jlrSenha;
    }
    
    public void setJlrSenha(String jlrSenha) {
        this.jlrSenha = jlrSenha;
    }

    
    @Column(name="jlr_nivel", nullable=false)
    public int getJlrNivel() {
        return this.jlrNivel;
    }
    
    public void setJlrNivel(int jlrNivel) {
        this.jlrNivel = jlrNivel;
    }

    
    @Column(name="jlr_ativo", nullable=false, length=1)
    public String getJlrAtivo() {
        return this.jlrAtivo;
    }
    
    public void setJlrAtivo(String jlrAtivo) {
        this.jlrAtivo = jlrAtivo;
    }

   @Override
    public boolean equals(Object object) {
        if (object instanceof JlrUsuarios) {
            JlrUsuarios jlrUsuarios = (JlrUsuarios) object;
            if (jlrUsuarios.getIdJlrUsuarios()== this.getIdJlrUsuarios()) {
                return true;
            }
        }
        return false;
    }

@Override
    public String toString() {
        return this.idJlrUsuarios + " - " + this.jlrNome;
    }



}


