package bean;
// Generated 17/09/2025 17:29:19 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "jlr_usuarios",
         catalog = "joao_roa"
)
public class JlrUsuarios implements java.io.Serializable {

    private int idJlrUsuarios;
    private String  jlrNome;
    private String jlrApelido;
    private String jlrCpf;
    private Date jlrDataNascimento;
    private String jlrSenha;
    private int jlrNivel;
    private String jlrAtivo;

    public JlrUsuarios() {
    }



    public JlrUsuarios(int idJlrUsuarios, String jlrNome, String jlrApelido, String jlrCpf, Date jlrDataNascimento, String jlrSenha, int jlrNivel, String jlrAtivo) {
        this.idJlrUsuarios = idJlrUsuarios;
        this.jlrNome = jlrNome;
        this.jlrApelido = jlrApelido;
        this.jlrCpf = jlrCpf;
        this.jlrDataNascimento = jlrDataNascimento;
        this.jlrSenha = jlrSenha;
        this.jlrNivel = jlrNivel;
        this.jlrAtivo = jlrAtivo;
    }

    @Id

    @Column(name = "id_jlr_usuarios", unique = true, nullable = false)
    public int getIdJlrUsuarios() {
        return this.idJlrUsuarios;
    }

    public void setIdJlrUsuarios(int idJlrUsuarios) {
        this.idJlrUsuarios = idJlrUsuarios;
    }

    @Column(name = "jlr_nome", nullable = false, length = 45)
    public String getJlrNome() {
        return this.jlrNome;
    }

    public void setJlrNome(String jlrNome) {
        this.jlrNome = jlrNome;
    }

    @Column(name = "jlr_apelido", nullable = false, length = 45)
    public String getJlrApelido() {
        return this.jlrApelido;
    }

    public void setJlrApelido(String jlrApelido) {
        this.jlrApelido = jlrApelido;
    }

    @Column(name = "jlr_cpf", length = 15)
    public String getJlrCpf() {
        return this.jlrCpf;
    }

    public void setJlrCpf(String jlrCpf) {
        this.jlrCpf = jlrCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "jlr_data_nascimento", length = 10)
    public Date getJlrDataNascimento() {
        return this.jlrDataNascimento;
    }

    public void setJlrDataNascimento(Date jlrDataNascimento) {
        this.jlrDataNascimento = jlrDataNascimento;
    }

    @Column(name = "jlr_senha", nullable = false, length = 15)
    public String getJlrSenha() {
        return this.jlrSenha;
    }

    public void setJlrSenha(String jlrSenha) {
        this.jlrSenha = jlrSenha;
    }

    @Column(name = "jlr_nivel", nullable = false)
    public int getJlrNivel() {
        return this.jlrNivel;
    }

    public void setJlrNivel(int jlrNivel) {
        this.jlrNivel = jlrNivel;
    }

    @Column(name = "jlr_ativo", nullable = false, length = 1)
    public String getJlrAtivo() {
        return this.jlrAtivo;
    }

    public void setJlrAtivo(String jlrAtivo) {
        this.jlrAtivo = jlrAtivo;
    }

}
