package bean;
// Generated 12/10/2025 19:53:29 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JlrVendasprodutos generated by hbm2java
 */
@Entity
@Table(name = "jlr_vendasprodutos",
         catalog = "joao_roa"
)
public class JlrVendasprodutos implements java.io.Serializable {

    private int idJlrVendasProdutos;
    private int jlrIdVendas;
    private int jlrProduto;
    private int jlrQuantidade;
    private String jlrPrecoUnitario;
    private String jlrDesconto;
    private String jlrTotal;

    public JlrVendasprodutos() {
    }

    public JlrVendasprodutos(int idJlrVendasProdutos, int jlrIdVendas, int jlrProduto, int jlrQuantidade, String jlrPrecoUnitario, String jlrDesconto, String jlrTotal) {
        this.idJlrVendasProdutos = idJlrVendasProdutos;
        this.jlrIdVendas = jlrIdVendas;
        this.jlrProduto = jlrProduto;
        this.jlrQuantidade = jlrQuantidade;
        this.jlrPrecoUnitario = jlrPrecoUnitario;
        this.jlrDesconto = jlrDesconto;
        this.jlrTotal = jlrTotal;
    }

    @Id

    @Column(name = "id_jlr_vendasProdutos", unique = true, nullable = false)
    public int getIdJlrVendasProdutos() {
        return this.idJlrVendasProdutos;
    }

    public void setIdJlrVendasProdutos(int idJlrVendasProdutos) {
        this.idJlrVendasProdutos = idJlrVendasProdutos;
    }

    @Column(name = "jlr_id_vendas", nullable = false)
    public int getJlrIdVendas() {
        return this.jlrIdVendas;
    }

    public void setJlrIdVendas(int jlrIdVendas) {
        this.jlrIdVendas = jlrIdVendas;
    }

    @Column(name = "jlr_produto", nullable = false)
    public int getJlrProduto() {
        return this.jlrProduto;
    }

    public void setJlrProduto(int jlrProduto) {
        this.jlrProduto = jlrProduto;
    }

    @Column(name = "jlr_quantidade", nullable = false)
    public int getJlrQuantidade() {
        return this.jlrQuantidade;
    }

    public void setJlrQuantidade(int jlrQuantidade) {
        this.jlrQuantidade = jlrQuantidade;
    }

    @Column(name = "jlr_preco_unitario", nullable = false, precision = 10)
    public String getJlrPrecoUnitario() {
        return this.jlrPrecoUnitario;
    }

    public void setJlrPrecoUnitario(String jlrPrecoUnitario) {
        this.jlrPrecoUnitario = jlrPrecoUnitario;
    }

    @Column(name = "jlr_desconto", nullable = false, precision = 10)
    public String getJlrDesconto() {
        return this.jlrDesconto;
    }

    public void setJlrDesconto(String jlrDesconto) {
        this.jlrDesconto = jlrDesconto;
    }

    @Column(name = "jlr_total", nullable = false, precision = 10)
    public String getJlrTotal() {
        return this.jlrTotal;
    }

    public void setJlrTotal(String jlrTotal) {
        this.jlrTotal = jlrTotal;
    }

}
