package bean;
// Generated 29/10/2025 15:23:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlrVendedor generated by hbm2java
 */
@Entity
@Table(name="jlr_vendedor"
    ,catalog="db_joao_roa"
)
public class JlrVendedor  implements java.io.Serializable {


     private int idJlrVendedor;
     private String jlrNome;
     private String jlrCpf;
     private String jlrTelefone;
     private String jlrEmail;
     private Date jlrDataNascimento;
     private String jlrAtivo;

    public JlrVendedor() {
    }

	
    public JlrVendedor(int idJlrVendedor, String jlrNome, String jlrCpf, String jlrTelefone, String jlrEmail, Date jlrDataNascimento, String jlrAtivo) {
        this.idJlrVendedor = idJlrVendedor;
        this.jlrNome = jlrNome;
        this.jlrCpf = jlrCpf;
        this.jlrTelefone = jlrTelefone;
        this.jlrEmail = jlrEmail;
        this.jlrDataNascimento = jlrDataNascimento;
        this.jlrAtivo = jlrAtivo;
    }

  
   
     @Id 

    
    @Column(name="id_jlr_vendedor", unique=true, nullable=false)
    public int getIdJlrVendedor() {
        return this.idJlrVendedor;
    }
    
    public void setIdJlrVendedor(int idJlrVendedor) {
        this.idJlrVendedor = idJlrVendedor;
    }

    
    @Column(name="jlr_nome", nullable=false, length=50)
    public String getJlrNome() {
        return this.jlrNome;
    }
    
    public void setJlrNome(String jlrNome) {
        this.jlrNome = jlrNome;
    }

    
    @Column(name="jlr_cpf", nullable=false, length=14)
    public String getJlrCpf() {
        return this.jlrCpf;
    }
    
    public void setJlrCpf(String jlrCpf) {
        this.jlrCpf = jlrCpf;
    }

    
    @Column(name="jlr_telefone", nullable=false, length=50)
    public String getJlrTelefone() {
        return this.jlrTelefone;
    }
    
    public void setJlrTelefone(String jlrTelefone) {
        this.jlrTelefone = jlrTelefone;
    }

    
    @Column(name="jlr_email", nullable=false, length=100)
    public String getJlrEmail() {
        return this.jlrEmail;
    }
    
    public void setJlrEmail(String jlrEmail) {
        this.jlrEmail = jlrEmail;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jlr_data_nascimento", nullable=false, length=10)
    public Date getJlrDataNascimento() {
        return this.jlrDataNascimento;
    }
    
    public void setJlrDataNascimento(Date jlrDataNascimento) {
        this.jlrDataNascimento = jlrDataNascimento;
    }

    
    @Column(name="jlr_ativo", nullable=false, length=15)
    public String getJlrAtivo() {
        return this.jlrAtivo;
    }
    
    public void setJlrAtivo(String jlrAtivo) {
        this.jlrAtivo = jlrAtivo;
    }
    
@Override
public String toString() {
        return this.idJlrVendedor + " - " + this.jlrNome;
    }

    @Override
    public boolean equals(Object object) {
        if (object instanceof JlrVendedor) {
            JlrVendedor jlrVendedor = (JlrVendedor) object;
            if (jlrVendedor.getIdJlrVendedor() == this.getIdJlrVendedor()) {
                return true;
            }
        }
        return false;
    }
}
//@Override
  //  public String toString() {
     //   return this.jlrNome;
   // }

