package bean;
// Generated 29/10/2025 15:23:18 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlrVendas generated by hbm2java
 */
@Entity
@Table(name="jlr_vendas"
    ,catalog="db_joao_roa"
)
public class JlrVendas  implements java.io.Serializable {


     private int idJlrVendas;
     private JlrClientes jlrClientes;
     private JlrUsuarios jlrUsuarios;
     private JlrVendedor jlrVendedor;
     private Date jlrData;
     private String jlrStatus;
     private Double jlrTotal;
   

    public JlrVendas() {
    }

	
    public JlrVendas(int idJlrVendas) {
        this.idJlrVendas = idJlrVendas;
    }
    public JlrVendas(int idJlrVendas, JlrClientes jlrClientes, JlrUsuarios jlrUsuarios, JlrVendedor jlrVendedor, Date jlrData, String jlrStatus, Double jlrTotal) {
       this.idJlrVendas = idJlrVendas;
       this.jlrClientes = jlrClientes;
       this.jlrUsuarios = jlrUsuarios;
       this.jlrVendedor = jlrVendedor;
       this.jlrData = jlrData;
       this.jlrStatus = jlrStatus;
       this.jlrTotal = jlrTotal;

    }
   
     @Id 

    
    @Column(name="id_jlr_vendas", unique=true, nullable=false)
    public int getIdJlrVendas() {
        return this.idJlrVendas;
    }
    
    public void setIdJlrVendas(int idJlrVendas) {
        this.idJlrVendas = idJlrVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jlr_id_clientes")
    public JlrClientes getJlrClientes() {
        return this.jlrClientes;
    }
    
    public void setJlrClientes(JlrClientes jlrClientes) {
        this.jlrClientes = jlrClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jlr_id_usuarios")
    public JlrUsuarios getJlrUsuarios() {
        return this.jlrUsuarios;
    }
    
    public void setJlrUsuarios(JlrUsuarios jlrUsuarios) {
        this.jlrUsuarios = jlrUsuarios;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jlr_id_vendedor")
    public JlrVendedor getJlrVendedor() {
        return this.jlrVendedor;
    }
    
    public void setJlrVendedor(JlrVendedor jlrVendedor) {
        this.jlrVendedor = jlrVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="jlr_data", length=10)
    public Date getJlrData() {
        return this.jlrData;
    }
    
    public void setJlrData(Date jlrData) {
        this.jlrData = jlrData;
    }

    
    @Column(name="jlr_status", length=20)
    public String getJlrStatus() {
        return this.jlrStatus;
    }
    
    public void setJlrStatus(String jlrStatus) {
        this.jlrStatus = jlrStatus;
    }

    
    @Column(name="jlr_total", precision=10)
    public Double getJlrTotal() {
        return this.jlrTotal;
    }
    
    public void setJlrTotal(Double jlrTotal) {
        this.jlrTotal = jlrTotal;
    }




}


