package bean;
// Generated 12/10/2025 19:53:29 by Hibernate Tools 4.3.1



import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JlrVendas generated by hbm2java
 */
@Entity
@Table(name="jlr_vendas"
    ,catalog="joao_roa"
)
public class JlrVendas  implements java.io.Serializable {


     private int idJlrVendas;
     private int jlrIdClientes;
     private int jlrIdUsuarios;
     private int jlrIdEntregas;
     private Date jlrDataHora;
     private String jlrStatus;
     private String jlrTotal;

    public JlrVendas() {
    }

	
    public JlrVendas(int idJlrVendas, int jlrIdClientes, int jlrIdUsuarios, int jlrIdEntregas, String jlrStatus, String jlrTotal) {
        this.idJlrVendas = idJlrVendas;
        this.jlrIdClientes = jlrIdClientes;
        this.jlrIdUsuarios = jlrIdUsuarios;
        this.jlrIdEntregas = jlrIdEntregas;
        this.jlrStatus = jlrStatus;
        this.jlrTotal = jlrTotal;
    }
    public JlrVendas(int idJlrVendas, int jlrIdClientes, int jlrIdUsuarios, int jlrIdEntregas, Date jlrDataHora, String jlrStatus, String jlrTotal) {
       this.idJlrVendas = idJlrVendas;
       this.jlrIdClientes = jlrIdClientes;
       this.jlrIdUsuarios = jlrIdUsuarios;
       this.jlrIdEntregas = jlrIdEntregas;
       this.jlrDataHora = jlrDataHora;
       this.jlrStatus = jlrStatus;
       this.jlrTotal = jlrTotal;
    }
   
     @Id 

    
    @Column(name="id_jlr_vendas", unique=true, nullable=false)
    public int getIdJlrVendas() {
        return this.idJlrVendas;
    }
    
    public void setIdJlrVendas(int idJlrVendas) {
        this.idJlrVendas = idJlrVendas;
    }

    
    @Column(name="jlr_id_clientes", nullable=false)
    public int getJlrIdClientes() {
        return this.jlrIdClientes;
    }
    
    public void setJlrIdClientes(int jlrIdClientes) {
        this.jlrIdClientes = jlrIdClientes;
    }

    
    @Column(name="jlr_id_usuarios", nullable=false)
    public int getJlrIdUsuarios() {
        return this.jlrIdUsuarios;
    }
    
    public void setJlrIdUsuarios(int jlrIdUsuarios) {
        this.jlrIdUsuarios = jlrIdUsuarios;
    }

    
    @Column(name="jlr_id_entregas", nullable=false)
    public int getJlrIdEntregas() {
        return this.jlrIdEntregas;
    }
    
    public void setJlrIdEntregas(int jlrIdEntregas) {
        this.jlrIdEntregas = jlrIdEntregas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="jlr_data_hora", length=19)
    public Date getJlrDataHora() {
        return this.jlrDataHora;
    }
    
    public void setJlrDataHora(Date jlrDataHora) {
        this.jlrDataHora = jlrDataHora;
    }

    
    @Column(name="jlr_status", nullable=false, length=20)
    public String getJlrStatus() {
        return this.jlrStatus;
    }
    
    public void setJlrStatus(String jlrStatus) {
        this.jlrStatus = jlrStatus;
    }

    
    @Column(name="jlr_total", nullable=false, precision=10)
    public String getJlrTotal() {
        return this.jlrTotal;
    }
    
    public void setJlrTotal(String jlrTotal) {
        this.jlrTotal = jlrTotal;
    }




}


