package bean;
// Generated 29/10/2025 15:23:18 by Hibernate Tools 4.3.1

import java.lang.Double;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JlrVendasprodutos generated by hbm2java
 */
@Entity
@Table(name = "jlr_vendasprodutos",
         catalog = "db_joao_roa"
)
public class JlrVendasprodutos implements java.io.Serializable {

    private int idJlrVendasProdutos;
    private JlrProdutos jlrProdutos;
    private JlrVendas jlrVendas;
    private int jlrQuantidade;
    private Double jlrValorUnitario;
    private Double jlrDesconto;

    public JlrVendasprodutos() {
    }

    public JlrVendasprodutos(int idJlrVendasProdutos) {
        this.idJlrVendasProdutos = idJlrVendasProdutos;
    }

    public JlrVendasprodutos(int idJlrVendasProdutos, JlrProdutos jlrProdutos, JlrVendas jlrVendas, Integer jlrQuantidade, Double jlrValorUnitario, Double jlrDesconto) {
        this.idJlrVendasProdutos = idJlrVendasProdutos;
        this.jlrProdutos = jlrProdutos;
        this.jlrVendas = jlrVendas;
        this.jlrQuantidade = jlrQuantidade;
        this.jlrValorUnitario = jlrValorUnitario;
        this.jlrDesconto = jlrDesconto;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)

    @Column(name = "id_jlr_vendasProdutos", unique = true, nullable = false)
    public int getIdJlrVendasProdutos() {
        return this.idJlrVendasProdutos;
    }

    public void setIdJlrVendasProdutos(int idJlrVendasProdutos) {
        this.idJlrVendasProdutos = idJlrVendasProdutos;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "jlr_produto")
    public JlrProdutos getJlrProdutos() {
        return this.jlrProdutos;
    }

    public void setJlrProdutos(JlrProdutos jlrProdutos) {
        this.jlrProdutos = jlrProdutos;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "jlr_id_vendas")
    public JlrVendas getJlrVendas() {
        return this.jlrVendas;
    }

    public void setJlrVendas(JlrVendas jlrVendas) {
        this.jlrVendas = jlrVendas;
    }

    @Column(name = "jlr_quantidade")
    public int getJlrQuantidade() {
        return this.jlrQuantidade;
    }

    public void setJlrQuantidade(int jlrQuantidade) {
        this.jlrQuantidade = jlrQuantidade;
    }

    @Column(name = "jlr_valor_unitario", precision = 10)
    public Double getJlrValorUnitario() {
        return this.jlrValorUnitario;
    }

    public void setJlrValorUnitario(Double jlrValorUnitario) {
        this.jlrValorUnitario = jlrValorUnitario;
    }

    @Column(name = "jlr_desconto", precision = 10)
    public Double getJlrDesconto() {
        return this.jlrDesconto;
    }

    public void setJlrDesconto(Double jlrDesconto) {
        this.jlrDesconto = jlrDesconto;
    }

}
